/**
 * License The Apache Software License, Version 2.0
 * Copyright (C) 2013-2013 Nicolas, Cecile - version 1.0-SNAPSHOT - All rights reserved.
 * Last modification 12-04-2013
 */

/**
 * #Generated by Git-Commit-Id-Plugin
 * #Fri Apr 12 15:50:05 CEST 2013
 * git.commit.id.abbrev=1acfa21
 * git.commit.user.email=nicolas.dufour@etu.univ-nantes.fr
 * git.commit.message.full=Merge branch 'master' of https\://github.com/NicoCec/Datatypes\n
 * git.commit.id=1acfa2181849a6bc1b0f6b63e4955312bbd93d4e
 * git.commit.message.short=Merge branch 'master' of https\://github.com/NicoCec/Datatypes
 * git.commit.user.name=NicoCec
 * git.build.user.name=NicoCec
 * git.commit.id.describe=1acfa21-dirty
 * git.build.user.email=nicolas.dufour@etu.univ-nantes.fr
 * git.branch=master
 * git.commit.time=12.04.2013 @ 15\:42\:43 CEST
 * git.build.time=12.04.2013 @ 15\:50\:05 CEST
 */

package fr.miage.temporel;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * 
 * @author E12B336Z
 */
public class IntervalleHoraire {
	
	private DateTempo dateDebut;
	private DateTempo dateFin;
        private List<EvenementRecurrent> evenementsRec = new ArrayList<EvenementRecurrent>();

    /**
     * Return the unmodifiable list of events
     * @return list of events
     */
    public List<EvenementRecurrent> getEvenementsRec() {
        return Collections.unmodifiableList(evenementsRec);
    }

    public void setEvenementsRec(List<EvenementRecurrent> evenementsRec) {
        this.evenementsRec = evenementsRec;
    }

    public IntervalleHoraire(DateTempo dateDebut, DateTempo dateFin) {
        this.dateDebut = dateDebut;
        this.dateFin = dateFin;
    }

    public DateTempo getDateDebut() {
        return dateDebut;
    }

    public void setDateDebut(DateTempo dateDebut) {
        this.dateDebut = dateDebut;
    }

    public DateTempo getDateFin() {
        return dateFin;
    }

    public void setDateFin(DateTempo dateFin) {
        this.dateFin = dateFin;
    }
	
    /**
     * Add an event to the current interval
     * @param evtRec 
     */
    public void addEvenementRec(EvenementRecurrent evtRec){
        evenementsRec.add(evtRec);
    }
    
    /**
     * Delete an event from the current interval
     * @param evtRec 
     */
    public void delEvenementRec(EvenementRecurrent evtRec){
        evenementsRec.remove(evtRec);
    }
    
    @Override
    public String toString(){
        return "date de début "+dateDebut.toString()
                +"date de fin "+dateFin.toString();
    }
}
