/**
 * License The Apache Software License, Version 2.0
 * Copyright (C) 2013-2013 Nicolas, Cecile - version 1.0-SNAPSHOT - All rights reserved.
 * Last modification 12-04-2013
 */

/**
 * #Generated by Git-Commit-Id-Plugin
 * #Fri Apr 12 15:50:05 CEST 2013
 * git.commit.id.abbrev=1acfa21
 * git.commit.user.email=nicolas.dufour@etu.univ-nantes.fr
 * git.commit.message.full=Merge branch 'master' of https\://github.com/NicoCec/Datatypes\n
 * git.commit.id=1acfa2181849a6bc1b0f6b63e4955312bbd93d4e
 * git.commit.message.short=Merge branch 'master' of https\://github.com/NicoCec/Datatypes
 * git.commit.user.name=NicoCec
 * git.build.user.name=NicoCec
 * git.commit.id.describe=1acfa21-dirty
 * git.build.user.email=nicolas.dufour@etu.univ-nantes.fr
 * git.branch=master
 * git.commit.time=12.04.2013 @ 15\:42\:43 CEST
 * git.build.time=12.04.2013 @ 15\:50\:05 CEST
 */

package fr.miage.adresses;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
/**
 * 
 * @author E12B336Z
 */
public class Ville {
	
	private String nomV;
        private List<Lieux> lieux = new ArrayList<Lieux>();

    public Ville(String nomV) {
        this.nomV = nomV;
    }



        
    public String getNomV() {
        return nomV;
    }

    public void setNomV(String nomV) {
        this.nomV = nomV;
    }

    /**
     * Retourn the unmodifiable list of places 
     * @return List<Lieux>
     */
    public List<Lieux> getLieux() {
        return Collections.unmodifiableList(lieux);
    }

    public void setLieux(List<Lieux> lieux) {
        this.lieux = lieux;
    }
    
    /**
     * Add a places in the town
     * @param lieu 
     */
    public void addLieu(Lieux lieu){
        lieux.add(lieu);
    }
    
    /**
     * Delete a place in the town
     * @param lieu 
     */
    public void delLieu(Lieux lieu){
        lieux.remove(lieu);
    }
  
}
