/**
 * License The Apache Software License, Version 2.0
 * Copyright (C) 2013-2013 Nicolas, Cecile - version 1.0-SNAPSHOT - All rights reserved.
 * Last modification 12-04-2013
 */

/**
 * #Generated by Git-Commit-Id-Plugin
 * #Fri Apr 12 15:50:05 CEST 2013
 * git.commit.id.abbrev=1acfa21
 * git.commit.user.email=nicolas.dufour@etu.univ-nantes.fr
 * git.commit.message.full=Merge branch 'master' of https\://github.com/NicoCec/Datatypes\n
 * git.commit.id=1acfa2181849a6bc1b0f6b63e4955312bbd93d4e
 * git.commit.message.short=Merge branch 'master' of https\://github.com/NicoCec/Datatypes
 * git.commit.user.name=NicoCec
 * git.build.user.name=NicoCec
 * git.commit.id.describe=1acfa21-dirty
 * git.build.user.email=nicolas.dufour@etu.univ-nantes.fr
 * git.branch=master
 * git.commit.time=12.04.2013 @ 15\:42\:43 CEST
 * git.build.time=12.04.2013 @ 15\:50\:05 CEST
 */

package fr.miage.mesures;

/**
 * 
 * @author E12B336Z
 */
public class Conversion {

	private double myQuantiteDep;
	private double myQuantiteArr;
	private Unite myUniteDep;
	private Unite myUniteArr;

    public Conversion(double myQuantiteDep, double myQuantiteArr, Unite myUniteDep, Unite myUniteArr) {
        this.myQuantiteDep = myQuantiteDep;
        this.myQuantiteArr = myQuantiteArr;
        this.myUniteDep = myUniteDep;
        this.myUniteArr = myUniteArr;
    }

    public double getMyQuantiteDep() {
        return myQuantiteDep;
    }

    public void setMyQuantiteDep(double myQuantiteDep) {
        this.myQuantiteDep = myQuantiteDep;
    }

    public double getMyQuantiteArr() {
        return myQuantiteArr;
    }

    public void setMyQuantiteArr(double myQuantiteArr) {
        this.myQuantiteArr = myQuantiteArr;
    }

    public Unite getMyUniteDep() {
        return myUniteDep;
    }

    public void setMyUniteDep(Unite myUniteDep) {
        this.myUniteDep = myUniteDep;
    }

    public Unite getMyUniteArr() {
        return myUniteArr;
    }

    public void setMyUniteArr(Unite myUniteArr) {
        this.myUniteArr = myUniteArr;
    }
	
    /**
     * 
     * @return all the informations about the conversion
     */
    @Override
    public String toString(){
        return "la conversion de "+myQuantiteDep+" "+myUniteDep.toString()
                +" en "+ myUniteArr.toString()+ " donne "+myQuantiteArr;
    }
}
