/**
 * License The Apache Software License, Version 2.0
 * Copyright (C) 2013-2013 Nicolas, Cecile - version 1.0-SNAPSHOT - All rights reserved.
 * Last modification 12-04-2013
 */

/**
 * #Generated by Git-Commit-Id-Plugin
 * #Fri Apr 12 15:50:05 CEST 2013
 * git.commit.id.abbrev=1acfa21
 * git.commit.user.email=nicolas.dufour@etu.univ-nantes.fr
 * git.commit.message.full=Merge branch 'master' of https\://github.com/NicoCec/Datatypes\n
 * git.commit.id=1acfa2181849a6bc1b0f6b63e4955312bbd93d4e
 * git.commit.message.short=Merge branch 'master' of https\://github.com/NicoCec/Datatypes
 * git.commit.user.name=NicoCec
 * git.build.user.name=NicoCec
 * git.commit.id.describe=1acfa21-dirty
 * git.build.user.email=nicolas.dufour@etu.univ-nantes.fr
 * git.branch=master
 * git.commit.time=12.04.2013 @ 15\:42\:43 CEST
 * git.build.time=12.04.2013 @ 15\:50\:05 CEST
 */

package main;

import java.util.ArrayList;

import Adresses.Pays;
import Financier.Conversion;
import Financier.Devise;
import Financier.Taux_de_conversion;

public class execution {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		
		ArrayList<Pays> listePays = new ArrayList<Pays>();
		Taux_de_conversion tx = new Taux_de_conversion(3.25);
		Devise devise_arr = new Devise("livre", listePays);
		
		Devise devise = new Devise("euro", listePays);
		
		devise.convertir(tx, devise_arr, 10000);
		
		
	}

}
