/**
 * License The Apache Software License, Version 2.0
 * Copyright (C) 2013-2013 Nicolas, Cecile - version 1.0-SNAPSHOT - All rights reserved.
 * Last modification 12-04-2013
 */

/**
 * #Generated by Git-Commit-Id-Plugin
 * #Fri Apr 12 15:50:05 CEST 2013
 * git.commit.id.abbrev=1acfa21
 * git.commit.user.email=nicolas.dufour@etu.univ-nantes.fr
 * git.commit.message.full=Merge branch 'master' of https\://github.com/NicoCec/Datatypes\n
 * git.commit.id=1acfa2181849a6bc1b0f6b63e4955312bbd93d4e
 * git.commit.message.short=Merge branch 'master' of https\://github.com/NicoCec/Datatypes
 * git.commit.user.name=NicoCec
 * git.build.user.name=NicoCec
 * git.commit.id.describe=1acfa21-dirty
 * git.build.user.email=nicolas.dufour@etu.univ-nantes.fr
 * git.branch=master
 * git.commit.time=12.04.2013 @ 15\:42\:43 CEST
 * git.build.time=12.04.2013 @ 15\:50\:05 CEST
 */

package fr.miage.financier;

import fr.miage.temporel.DateTempo;

/**
 * 
 * @author E12B336Z
 */
public class Conversion {

	private double montantDepart;
	private double montantArrivee;
        private Devise deviseDepart;
	private Devise deviseArrivee;
	private DateTempo dateConv;
        
    public double getMontantDepart() {
        return montantDepart;
    }

    public void setMontantDepart(double montantDepart) {
        this.montantDepart = montantDepart;
    }

    public double getMontantArrivee() {
        return montantArrivee;
    }

    public void setMontantArrivee(double montantArrivee) {
        this.montantArrivee = montantArrivee;
    }

    public Devise getDeviseDepart() {
        return deviseDepart;
    }

    public void setDeviseDepart(Devise deviseDepart) {
        this.deviseDepart = deviseDepart;
    }

    public Devise getDeviseArrivee() {
        return deviseArrivee;
    }

    public void setDeviseArrivee(Devise deviseArrivee) {
        this.deviseArrivee = deviseArrivee;
    }

    public DateTempo getDateConv() {
        return dateConv;
    }

    public void setDateConv(DateTempo dateConv) {
        this.dateConv = dateConv;
    }
	
	
    public Conversion(double montantDepart,
                    double montantArrivee, Devise deviseDepart, Devise deviseArrivee, DateTempo date) {
            this.montantDepart = montantDepart;
            this.montantArrivee = montantArrivee;
            this.deviseDepart = deviseDepart;
            this.deviseArrivee = deviseArrivee;
            this.dateConv = date;
    }
    
    /**
     * 
     * @return all the informations about the conversion
     */
    @Override
    public String toString(){
        return "la conversion de "+montantDepart+" "+deviseDepart.toString()
                +" en "+ deviseArrivee.toString()+ " donne "+montantArrivee
                + " le "+ dateConv.toString();
    }
	
}
