/**
 * License The Apache Software License, Version 2.0
 * Copyright (C) 2013-2013 Nicolas, Cecile - version 1.0-SNAPSHOT - All rights reserved.
 * Last modification 12-04-2013
 */

/**
 * #Generated by Git-Commit-Id-Plugin
 * #Fri Apr 12 15:50:05 CEST 2013
 * git.commit.id.abbrev=1acfa21
 * git.commit.user.email=nicolas.dufour@etu.univ-nantes.fr
 * git.commit.message.full=Merge branch 'master' of https\://github.com/NicoCec/Datatypes\n
 * git.commit.id=1acfa2181849a6bc1b0f6b63e4955312bbd93d4e
 * git.commit.message.short=Merge branch 'master' of https\://github.com/NicoCec/Datatypes
 * git.commit.user.name=NicoCec
 * git.build.user.name=NicoCec
 * git.commit.id.describe=1acfa21-dirty
 * git.build.user.email=nicolas.dufour@etu.univ-nantes.fr
 * git.branch=master
 * git.commit.time=12.04.2013 @ 15\:42\:43 CEST
 * git.build.time=12.04.2013 @ 15\:50\:05 CEST
 */

package fr.miage.financier;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;

import fr.miage.temporel.DateTempo;
import fr.miage.temporel.Heure;

import fr.miage.adresses.PaysAdresse;
import java.util.Collections;
import java.util.List;

/**
 * 
 * @author E12B336Z
 */
public class Devise {

	private String nom;
	private List<PaysAdresse> myListePays = new ArrayList<PaysAdresse>();
	
	public Devise(String nom) {
		this.nom = nom;
	}

        /**
         * Add the country where is the currency
         * @param pays 
         */
	public void ajouterPays(PaysAdresse pays){
		myListePays.add(pays);
	}
	
        /**
         * Delete a country where was a currency
         * @param pays 
         */
	public void supprimerPays(PaysAdresse pays){
		myListePays.remove(pays);
	}
	
        /**
         * Convert an amount in a specific currency to an other currency.
         * This function return a Conversion object, which contains all informations about this conversion

         * @param taux
         * @param deviseArr
         * @param montantDep
         * @return Conversion
         */
	public Conversion convertir(TauxDeConversion taux, Devise deviseArr, double montantDep){
		
                double montantArr = montantDep*taux.getTaux();
		
		Calendar calendar = new GregorianCalendar();
		int annee = calendar.get(Calendar.YEAR);
		int mois = calendar.get(Calendar.MONTH);
		mois +=1;
		int jour = calendar.get(Calendar.DAY_OF_MONTH);
		
		int heure = calendar.get(Calendar.HOUR_OF_DAY);
		int minute = calendar.get(Calendar.MINUTE);
		int seconde = calendar.get(Calendar.SECOND);
		
		//System.out.println("a : "+annee+", m : "+mois+", j : "+jour+", h : "+heure+", m : "+minute+", s : "+seconde);
		
		Heure heureConv = new Heure(heure, minute, seconde);
		DateTempo dateConv = new DateTempo(jour, mois, annee, heureConv);
		
		return new Conversion(montantDep, montantArr, this, deviseArr, dateConv); 
	}

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    /**
     * Return the list of country where is the currency.
     * La liste n'est pas modifiable
     * @return List<PaysAdresse>
     */
    public List<PaysAdresse> getMyListePays() {
        return Collections.unmodifiableList(myListePays);
    }

    public void setMyListePays(List<PaysAdresse> myListePays) {
        this.myListePays = myListePays;
    }

    @Override
    public String toString(){
        return nom;
    }
}
