/**
 * License The Apache Software License, Version 2.0
 * Copyright (C) 2013-2013 Nicolas, Cecile - version 1.0-SNAPSHOT - All rights reserved.
 * Last modification 12-04-2013
 */

/**
 * #Generated by Git-Commit-Id-Plugin
 * #Fri Apr 12 15:50:05 CEST 2013
 * git.commit.id.abbrev=1acfa21
 * git.commit.user.email=nicolas.dufour@etu.univ-nantes.fr
 * git.commit.message.full=Merge branch 'master' of https\://github.com/NicoCec/Datatypes\n
 * git.commit.id=1acfa2181849a6bc1b0f6b63e4955312bbd93d4e
 * git.commit.message.short=Merge branch 'master' of https\://github.com/NicoCec/Datatypes
 * git.commit.user.name=NicoCec
 * git.build.user.name=NicoCec
 * git.commit.id.describe=1acfa21-dirty
 * git.build.user.email=nicolas.dufour@etu.univ-nantes.fr
 * git.branch=master
 * git.commit.time=12.04.2013 @ 15\:42\:43 CEST
 * git.build.time=12.04.2013 @ 15\:50\:05 CEST
 */

package fr.miage.adresses;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 * @author E12B336Z
 */
public class EmailTest {
    
    public EmailTest() {
    }
    
    @BeforeClass
    public static void setUpClass() {
    }
    
    @AfterClass
    public static void tearDownClass() {
    }
    
    @Before
    public void setUp() {
    }
    
    @After
    public void tearDown() {
    }

    /**
     * Test of getMyNomDomaine method, of class Email.
     */
    //@Test
    /*public void testGetMyNomDomaine() {
        System.out.println("getMyNomDomaine");
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }*/

    /**
     * Test of setMyNomDomaine method, of class Email.
     */
    //@Test
    /*public void testSetMyNomDomaine() {
        System.out.println("setMyNomDomaine");
        NomDomaine myNomDomaine = null;
        Email instance = null;
        instance.setMyNomDomaine(myNomDomaine);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }*/

    /**
     * Test of getMyNomUtilisateur method, of class Email.
     */
    //@Test
    /*public void testGetMyNomUtilisateur() {
        System.out.println("getMyNomUtilisateur");
        Email instance = null;
        NomUtilisateur expResult = null;
        NomUtilisateur result = instance.getMyNomUtilisateur();
        assertEquals(expResult, result);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }*/

    /**
     * Test of setMyNomUtilisateur method, of class Email.
     */
    //@Test
     /*public void testSetMyNomUtilisateur() {
       System.out.println("setMyNomUtilisateur");
        NomUtilisateur myNomUtilisateur = null;
        Email instance = null;
        instance.setMyNomUtilisateur(myNomUtilisateur);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }*/

    /**
     * Test of toString method, of class Email.
     */
    //@Test
    /*public void testToString() {
        System.out.println("toString");
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }*/
}
